.PHONY: clean All

All:
	@echo "----------Building project:[ CodeLiteCpp - Debug ]----------"
	@"$(MAKE)" -f  "CodeLiteCpp.mk"
clean:
	@echo "----------Cleaning project:[ CodeLiteCpp - Debug ]----------"
	@"$(MAKE)" -f  "CodeLiteCpp.mk" clean
